app_command:
    resource: "@AppCommandBundle/Resources/config/routing.yml"
    prefix:   /

app_demo:
    resource: "@AppDemoBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
